.github/workflows/ci.yml
.rubocop.yml
temporal.gemspec

Enable `rubocop` for code linting
To ensure style consistency

[Feature] Enable rubocop linter

---

bridge/Cargo.lock
bridge/Cargo.toml
bridge/src/connection.rs

Replace Error boilerplate with `thiserror`
Simplifies Connection code and provides a better pattern for error definition moving forward
1. Closes #24 
Behaviour hasn't changed, relying on existing specs to catch any errors
No

[Refactor] Reduce Error boilerplate with thiserror

---

bridge/Cargo.lock
bridge/Cargo.toml
bridge/src/lib.rs
bridge/src/runtime.rs
bridge/src/worker.rs
lib/temporal/connection.rb
lib/temporal/runtime.rb
sig/temporal/bridge.rbs
sig/temporal/runtime.rbs
spec/unit/temporal/runtime_spec.rb

This PR is a refactor as suggested previously in #7. It consists of the following changes:
1. Removes all the global state from the Rust Bridge in favour of using a singleton in Ruby that represents the Runtime
2. Switches from using a channel with a loop for message processing to `tokio::runtime::spawn` for async tasks. This way it is much clearer what is going on
This PR is missing the logic to join on all the join handlers returned by the `spawn` to ensure no `panic`s are ignored. This will be implemented in a follow-up PR.
This should make everything more readable and improve the code quality
1. Closes #31 
4. How was this tested:
Tested locally with a script. Proper tests will be added when a Ruby worker is implemented
5. Any docs updates needed?
No

[Refactor] Reduce globals by introducing a Ruby singleton Runtime

---

.rubocop.yml
lib/temporal/client/implementation.rb
lib/temporal/client/workflow_handle.rb
sig/temporal/client/implementation.rbs
sig/temporal/client/workflow_handle.rbs
spec/integration/client_spec.rb
spec/unit/temporal/client/implementation_spec.rb
spec/unit/temporal/client/workflow_handle_spec.rb

A follow up to #39 which implements a `follow_runs` option for the workflow handle

[Follow-up] Implement `follow_runs` for workflow results

---

bridge/src/connection.rs
bridge/src/lib.rs
lib/temporal/client.rb
lib/temporal/client/implementation.rb
lib/temporal/client/workflow_handle.rb
lib/temporal/connection.rb
lib/temporal/interceptor/client.rb
sig/temporal/bridge.rbs
sig/temporal/client.rbs
sig/temporal/client/implementation.rbs
sig/temporal/client/workflow_handle.rbs
sig/temporal/connection.rbs
sig/temporal/interceptor/client.rbs
spec/integration/connection_spec.rb
spec/unit/temporal/client/implementation_spec.rb
spec/unit/temporal/client/workflow_handle_spec.rb
spec/unit/temporal/client_spec.rb

This is a follow up to the #39 adding support for RPC metadata and timeouts to be passed via `Client` and `WorkflowHandle`

[Follow-up] Support RPC metadata and timeouts

---

lib/temporal/client.rb
lib/temporal/data_converter.rb
sig/temporal/client.rbs
sig/temporal/data_converter.rbs
spec/unit/temporal/client/implementation_spec.rb
spec/unit/temporal/client_spec.rb
spec/unit/temporal/workflow/execution_info_spec.rb

This PR adds the option for the user to provide custom Payload Convert, Payload Codecs and Failure Converter to the Client.
1. Closes #58 
Tests added/updated
Yes, inline docs updated

[Feature] Allow configuring payload converter, codecs and failure converter

---

.github/workflows/ci.yml

Add caches for Rust and Go builds to speed up CI run times

[CI] Add Rust and Go CI caches for faster builds

---

.github/workflows/ci.yml
spec/integration/client_spec.rb
spec/integration/connection_spec.rb

Enable matrix CI runs for ruby 2.7, 3.0 and 3.1 on ubuntu and macos (windows will be added later)
Preparing for the first public release of the Client

[CI] Enable matrix CI runs different Ruby versions and OSs

---

spec/integration/client_spec.rb
spec/integration/connection_spec.rb
spec/support/helpers/test_rpc.rb
spec/support/mock_server.rb

This is a fix that spawns the mock server independently of the spec process. For some reason forking a mock server creates some resource contention in `tokio` that often leads to failing specs

[Fix] Specs failing to shutdown the mock server properly

---

lib/temporal/client.rb
lib/temporal/data_converter.rb
lib/temporal/failure_converter.rb
lib/temporal/worker.rb
sig/temporal/client.rbs
sig/temporal/data_converter.rbs
sig/temporal/worker.rbs
spec/unit/temporal/client_spec.rb
spec/unit/temporal/data_converter_spec.rb
spec/unit/temporal/worker_spec.rb

This PR modifies `Client` and `Worker` interfaces to accept a single `DataConverter` as an argument instead of individual pieces(payload converter, codecs and failure converter).
It also includes a bug fix for the `DataConverter#to_payload` and `DataConverter#from_payload` to use codecs.
This is one of the follow-ups to #74 
1. Closes 
#75 
#77 
Specs and RBS updated
Inline documentation has been updated

[Fix] DataConverter improvements

---

bridge/src/lib.rs
bridge/src/worker.rs
lib/temporal/bridge.rb
lib/temporal/bridge/error.rb
lib/temporal/worker.rb
lib/temporal/worker/activity_worker.rb
lib/temporal/worker/sync_worker.rb
sig/async.rbs
sig/temporal/bridge.rbs
sig/temporal/bridge/error.rbs
sig/temporal/worker.rbs
sig/temporal/worker/activity_worker.rbs
sig/temporal/worker/sync_worker.rbs
spec/integration/activity_worker_spec.rb
spec/unit/temporal/worker/activity_worker_spec.rb
spec/unit/temporal/worker/sync_worker_spec.rb
spec/unit/temporal/worker_spec.rb

This PR adds a proper shutdown procedure that interacts with the Core and waits for all the running tasks to finish.
Please bear in mind that this does not yet include the previously discussed changes to the `Worker#run` method (run until). These will be added after this PR.
1. Closes #87 
Tested against a running Temporal Server. Unit and integration specs updated
README and YARD docs will be updated separately #88

[Feature] Activity worker shutdown

---

bridge/Cargo.lock
bridge/Cargo.toml
bridge/src/connection.rs
bridge/src/lib.rs
spec/integration/client_spec.rb

This PR addresses the issue of Connection unable to respond to Ruby interrupts. This can happen when `Thread#raise` is called explicitly or when a Ruby program gets terminated with Ctrl+C mid execution (and falls into an outside of GVL blocking call).
The new implementation waits on a channel rather than a blocking `Runtime::block_on` and then returns an error when Ruby interrupt was requested.
This is required to make sure our Client plays well with Activity cancellations and propagating fatal Core error on shutdown.
1. Closes #96 
2. Closes #95 
3. How was this tested:
Integration spec that exposes the issue added
4. Any docs updates needed?
No

[Fix] Make Bridge Connection respond to Ruby interrupts

---

.rubocop.yml
lib/temporalio.rb
lib/temporalio/errors.rb
lib/temporalio/worker.rb
lib/temporalio/worker/activity_worker.rb
lib/temporalio/worker/runner.rb
sig/ruby.rbs
sig/temporalio/errors.rbs
sig/temporalio/worker.rbs
sig/temporalio/worker/activity_worker.rbs
sig/temporalio/worker/runner.rbs
spec/integration/activity_worker_spec.rb
spec/integration/worker_runner_spec.rb
spec/unit/temporalio/worker/activity_worker_spec.rb
spec/unit/temporalio/worker/runner_spec.rb
spec/unit/temporalio/worker_spec.rb

As discussed previously this PR improves the `Worker#run` interface and allows the users to run multiple workers at the same time without having to manage Threads themselves.
The new interface the following:
```ruby
worker_1 = Temporal::Worker.new(...)
worker_1.run # run a single worker indefinitely while waiting for a manual shutdown or a fatal error
worker_1.run do
sleep 10
end
worker_2 = Temporal::Worker.new(...)
Temporal::Worker.run(worker_1, worker_2) 
Temporal::Worker.run(worker_1, worker_2) do
sleep 10
end
```
What is not yet implemented is shutting down workers based on an external signal #98
1. Closes #86 
Both unit tests and integration test added/updated
Will be addressed separate before the release — #88

[Feature] Improve `Worker#run`

---

.rubocop.yml
README.md
lib/temporalio/activity/context.rb
lib/temporalio/errors.rb
lib/temporalio/worker.rb
lib/temporalio/worker/activity_runner.rb
lib/temporalio/worker/activity_worker.rb
lib/temporalio/worker/runner.rb
sig/async.rbs
sig/temporalio/activity/context.rbs
sig/temporalio/errors.rbs
sig/temporalio/worker.rbs
sig/temporalio/worker/activity_runner.rbs
sig/temporalio/worker/activity_worker.rbs
sig/temporalio/worker/runner.rbs
spec/integration/activity_worker_spec.rb
spec/integration/worker_runner_spec.rb
spec/support/go_worker/main.go
spec/unit/temporalio/activity/context_spec.rb
spec/unit/temporalio/worker/activity_worker_spec.rb
spec/unit/temporalio/worker_spec.rb

This PR adds 2 new features to the `Worker`:
1. Allow users to specify process signals to result in a worker shutdown procedure
2. Allow users to specify a graceful shutdown timeout after which running activities will get cancelled (but still waited on indefinitely)
P.S. This is not yet ready for a review because there's an issue — for some Temporal Server ignores failures of a type "cancelled_failure" when delivered outside of an activity cancellation request.
1. Closes #98 
2. Closes #92 
4. How was this tested:
Unit and integration specs added
5. Any docs updates needed?
README and YARD docs updated

[Feature] Implement Worker cancellation on signals and graceful shutdown timeout

---

.rubocop.yml
lib/temporalio/activity/context.rb
lib/temporalio/interceptor/activity_inbound.rb
lib/temporalio/interceptor/activity_outbound.rb
lib/temporalio/interceptor/chain.rb
lib/temporalio/interceptor/client.rb
lib/temporalio/worker.rb
lib/temporalio/worker/activity_runner.rb
lib/temporalio/worker/activity_worker.rb
sig/temporalio/activity/context.rbs
sig/temporalio/client.rbs
sig/temporalio/client/implementation.rbs
sig/temporalio/interceptor/activity_inbound.rbs
sig/temporalio/interceptor/activity_outbound.rbs
sig/temporalio/interceptor/chain.rbs
sig/temporalio/interceptor/client.rbs
sig/temporalio/worker.rbs
sig/temporalio/worker/activity_runner.rbs
sig/temporalio/worker/activity_worker.rbs
spec/integration/activity_worker_spec.rb
spec/integration/client_spec.rb
spec/support/helpers/test_capture_interceptor.rb
spec/support/helpers/test_simple_interceptor.rb
spec/unit/temporalio/activity/context_spec.rb
spec/unit/temporalio/interceptor/activity_inbound_spec.rb
spec/unit/temporalio/interceptor/activity_outbound_spec.rb
spec/unit/temporalio/interceptor/chain_spec.rb
spec/unit/temporalio/interceptor/client_spec.rb
spec/unit/temporalio/worker/activity_runner_spec.rb
spec/unit/temporalio/worker/activity_worker_spec.rb

This PR introduces inbound and outbound interceptors for activities. It also modifies the interceptor interface (from a superclass to a mixin), allowing a single class to implement multiple interceptors:
```ruby
class MyInterceptor
include Temporalio::Interceptor::ActivityInbound
include Temporalio::Interceptor::Client
def execute_activity(input)
...
super
end
def start_workflow(input)
...
super
end
end
```
1. Closes #85 
Both unit tests and integration tests added
Inline docs were updated

[Feature] Activity Interceptors

---

bridge/Cargo.lock
bridge/src/connection.rs
bridge/src/lib.rs
bridge/src/runtime.rs
bridge/src/test_server.rs
bridge/src/worker.rs
lib/gen/temporal/api/common/v1/message_pb.rb
lib/gen/temporal/api/history/v1/message_pb.rb
lib/gen/temporal/api/workflowservice/v1/request_response_pb.rb
lib/temporalio/worker.rb
lib/temporalio/worker/activity_worker.rb
sig/protos/temporal/api/common/v1/message.rbs
sig/protos/temporal/api/history/v1/message.rbs
sig/protos/temporal/api/workflowservice/v1/request_response.rbs
sig/temporalio/bridge.rbs
sig/temporalio/worker/activity_worker.rbs
spec/unit/temporalio/worker_spec.rb

- Update sdk-core to [09a2e4](https://github.com/temporalio/sdk-core/commit/09a2e4fc2198a8906bdb3f5051531578d9c46973)
- Refactor worker shutdown process as required by latest sdk-core

chore(core): Update sdk-core and refactor shutdown process

---

.gitignore
Gemfile.lock
bridge/Cargo.lock
bridge/Cargo.toml
lib/temporalio/bridge.rb
lib/temporalio/version.rb
lib/thermite_patch.rb
sig/thermite_patch.rbs
temporalio.gemspec

- Include RBS files in bundled Gems. Should hopefully fix #134.
- Make sure `ld` build flag `-Wl,-undefined,dynamic_lookup` is always present on OSX. This fixes a build issue causing `Undefined symbols for architecture arm64` errors if Ruby was built with XCode 14+.
- Bump version number to 0.1.1, in prep for a new release.

Fix multiple build/release issues

---

.github/workflows/build-native-ext.yml

- Updated CI workflow to use the correct file name pattern when looking for generated bridge's tar.gz file

fix(ci): Fix incorrect build artifact name

---

.github/workflows/build-gems.yml
README.md
temporalio/Rakefile
temporalio/lib/temporalio/version.rb
temporalio/temporalio.gemspec

* Update version to `0.2.0` instead of `0.2.0-alpha` for a couple of reasons:
* We have existing Ruby gems that cannot easily be yanked (past 30d window)
* rubydoc.info does not have API docs for prerelease
* Add source gem
* Make sure gemspec and other files are in gem
* README changes
Acknowledged that we can alter the smoke test to do higher-level gem install test to ensure compatibility, but that can be done separately.

Update version to not mark gem as prerelease and add source gem

---

temporalio/Cargo.lock
temporalio/Rakefile
temporalio/ext/Cargo.toml
temporalio/ext/src/client.rs
temporalio/lib/temporalio/client.rb
temporalio/lib/temporalio/client/async_activity_handle.rb
temporalio/lib/temporalio/client/connection/cloud_service.rb
temporalio/lib/temporalio/client/connection/operator_service.rb
temporalio/lib/temporalio/client/connection/service.rb
temporalio/lib/temporalio/client/connection/workflow_service.rb
temporalio/lib/temporalio/client/interceptor.rb
temporalio/lib/temporalio/client/workflow_handle.rb
temporalio/lib/temporalio/client/workflow_update_handle.rb
temporalio/lib/temporalio/internal/bridge/client.rb
temporalio/lib/temporalio/internal/client/implementation.rb
temporalio/sig/temporalio/client.rbs
temporalio/sig/temporalio/client/async_activity_handle.rbs
temporalio/sig/temporalio/client/connection/cloud_service.rbs
temporalio/sig/temporalio/client/connection/operator_service.rbs
temporalio/sig/temporalio/client/connection/service.rbs
temporalio/sig/temporalio/client/connection/workflow_service.rbs
temporalio/sig/temporalio/client/interceptor.rbs
temporalio/sig/temporalio/client/workflow_handle.rbs
temporalio/sig/temporalio/client/workflow_update_handle.rbs
temporalio/sig/temporalio/internal/bridge/client.rbs
temporalio/test/client_workflow_test.rb

* Added ability to provide `Cancellation` to all RPC calls to cancel them
* Move `rpc_metadata` and `rpc_timeout` (and low-level `rpc_retry`) into `Client::RPCOptions` along with this new `cancellation` field
* 3, sometimes 4 kwargs for advanced RPC options that are rarely set became too much
1. Closes #168

RPC cancellation support

---

temporalio/.rubocop.yml
temporalio/lib/temporalio/client.rb
temporalio/lib/temporalio/client/interceptor.rb
temporalio/lib/temporalio/client/schedule.rb
temporalio/lib/temporalio/client/schedule_handle.rb
temporalio/lib/temporalio/client/workflow_execution.rb
temporalio/lib/temporalio/converters/failure_converter.rb
temporalio/lib/temporalio/error.rb
temporalio/lib/temporalio/internal/client/implementation.rb
temporalio/lib/temporalio/internal/proto_utils.rb
temporalio/lib/temporalio/internal/worker/activity_worker.rb
temporalio/lib/temporalio/retry_policy.rb
temporalio/lib/temporalio/search_attributes.rb
temporalio/lib/temporalio/worker.rb
temporalio/sig/temporalio/client.rbs
temporalio/sig/temporalio/client/interceptor.rbs
temporalio/sig/temporalio/client/schedule.rbs
temporalio/sig/temporalio/client/schedule_handle.rbs
temporalio/sig/temporalio/internal/proto_utils.rbs
temporalio/sig/temporalio/retry_policy.rbs
temporalio/sig/temporalio/search_attributes.rbs
temporalio/sig/temporalio/worker/interceptor.rbs
temporalio/test/client_schedule_test.rb
temporalio/test/sig/test.rbs
temporalio/test/test.rb

Added schedule support in client similar to how was done in every other SDK. Also caused very minor/inconsequential refactoring of non-schedule code. Apologies for large surface area, schedules is a fairly large API.
1. Closes #163

Support for schedules

---

temporalio/.rubocop.yml
temporalio/ext/src/lib.rs
temporalio/ext/src/metric.rs
temporalio/lib/temporalio/activity/context.rb
temporalio/lib/temporalio/internal/metric.rb
temporalio/lib/temporalio/internal/worker/activity_worker.rb
temporalio/lib/temporalio/metric.rb
temporalio/lib/temporalio/runtime.rb
temporalio/sig/temporalio/activity/context.rbs
temporalio/sig/temporalio/internal/bridge/metric.rbs
temporalio/sig/temporalio/internal/metric.rbs
temporalio/sig/temporalio/internal/worker/activity_worker.rbs
temporalio/sig/temporalio/metric.rbs
temporalio/sig/temporalio/runtime.rbs
temporalio/test/runtime_test.rb
temporalio/test/sig/runtime_test.rbs
temporalio/test/sig/test.rbs
temporalio/test/test.rb
temporalio/test/worker_activity_test.rb

* Added `Temporalio::Metric::Meter` and `Temporalio::Metric` and supporting structure
* Exposed `metric_meter` in `Temporalio::Runtime` and `Temporalio::Activity::Context` for use by users
1. Closes #169

Metric meter support

---

README.md
temporalio/lib/temporalio/activity/definition.rb
temporalio/lib/temporalio/internal/worker/activity_worker.rb
temporalio/lib/temporalio/internal/worker/workflow_instance/outbound_implementation.rb
temporalio/lib/temporalio/workflow/definition.rb
temporalio/sig/temporalio/activity/definition.rbs
temporalio/test/worker_activity_test.rb

* Add `activity_dynamic` as an option for activity definitions (marks an activity as dynamic)
* Add `activity_raw_args` as an option for activity definitions (marks an activity as wanting to receive raw args)
Both of these match dynamic workflow, signal, query, and update support today.
1. Closes #166

Dynamic activities

---

.github/workflows/ci.yml
temporalio/ext/src/client.rs
temporalio/lib/temporalio/client/connection.rb
temporalio/sig/temporalio/client/connection.rbs
temporalio/sig/temporalio/internal/bridge/client.rbs
temporalio/test/client_cloud_test.rb

* Add `api_key` getter/setter on connection
* Add `rpc_metadata` getter/setter on connection
* Add cloud connectivity tests
1. Closes #164

Cloud test and support for updating API keys and RPC metadata

---

README.md
temporalio/Cargo.lock
temporalio/ext/Cargo.toml
temporalio/ext/src/worker.rs
temporalio/lib/temporalio/internal/worker/workflow_worker.rb
temporalio/lib/temporalio/worker.rb
temporalio/lib/temporalio/worker/tuner.rb
temporalio/lib/temporalio/worker/workflow_executor.rb
temporalio/lib/temporalio/worker/workflow_executor/thread_pool.rb
temporalio/lib/temporalio/worker/workflow_replayer.rb
temporalio/lib/temporalio/workflow_history.rb
temporalio/sig/temporalio/internal/bridge/worker.rbs
temporalio/sig/temporalio/internal/worker/multi_runner.rbs
temporalio/sig/temporalio/internal/worker/workflow_worker.rbs
temporalio/sig/temporalio/worker.rbs
temporalio/sig/temporalio/worker/tuner.rbs
temporalio/sig/temporalio/worker/workflow_executor.rbs
temporalio/sig/temporalio/worker/workflow_executor/thread_pool.rbs
temporalio/sig/temporalio/worker/workflow_replayer.rbs
temporalio/sig/temporalio/workflow_history.rbs
temporalio/test/worker/workflow_replayer_test.rb

* Added `Temporalio::Worker::WorkflowReplayer`
* Added Rust bridge impl
* Reworked internals to allow replayers and workers to share the `MultiRunner`
* When https://github.com/temporalio/sdk-core/issues/865 done, this will raise for task failure too
* README updates and tests
* Added to/from JSON helpers to `Temporalio::WorkflowHistory`
1. Closes #187

Workflow replayer support

---

temporalio/lib/temporalio/activity/context.rb
temporalio/lib/temporalio/activity/definition.rb
temporalio/lib/temporalio/internal/worker/activity_worker.rb
temporalio/lib/temporalio/internal/worker/workflow_instance/context.rb
temporalio/lib/temporalio/testing/activity_environment.rb
temporalio/lib/temporalio/workflow.rb
temporalio/sig/temporalio/activity/context.rbs
temporalio/sig/temporalio/activity/definition.rbs
temporalio/sig/temporalio/internal/worker/activity_worker.rbs
temporalio/sig/temporalio/internal/worker/workflow_instance.rbs
temporalio/sig/temporalio/internal/worker/workflow_instance/context.rbs
temporalio/sig/temporalio/workflow.rbs
temporalio/test/worker_activity_test.rb
temporalio/test/worker_workflow_test.rb
temporalio/test/workflow_utils.rb

* Added `Temporalio::Activity::Context#instance` to access the activity instance
* Added `Temporalio::Workflow.instance` to access the workflow instance
1. Closes #180

Workflow and activity instance access from context

---

.github/workflows/ci.yml
README.md

* Add upload for ruby.temporal.io
* Update README to point there
1. Closes #211

Setup doc upload for ruby.temporal.io

---

.github/workflows/build-gems.yml
.github/workflows/ci.yml
README.md
temporalio/smoke_test/smoke_test_gem.rb

* Updated (and tested) the build-gems.yml CI workflow to build musl gems
* Did not do in Alpine-based regular CI (requires lots of changes because setup-ruby and other things don't work there, and we have smoke test anyways)
* Updated smoke test to run in Alpine container
* Due to https://github.com/protocolbuffers/protobuf/issues/16853, had to use "ruby" platform Google Protobuf gem in smoke test (builds manually on install)
* Updated README
1. Closes #215

MUSL support

---

temporalio/temporalio.gemspec

Downgraded minimum protobuf version needed to 3.25. This is needed to interoperate with https://github.com/coinbase/temporal-ruby (along with https://github.com/coinbase/temporal-ruby/pull/335 from that side)

Downgrade minimum protobuf version needed to 3.25

---

temporalio/lib/temporalio/activity/context.rb
temporalio/lib/temporalio/internal/worker/activity_worker.rb
temporalio/lib/temporalio/testing/activity_environment.rb
temporalio/lib/temporalio/worker.rb
temporalio/sig/temporalio/activity/context.rbs
temporalio/sig/temporalio/internal/worker/activity_worker.rbs
temporalio/sig/temporalio/testing/activity_environment.rbs
temporalio/sig/temporalio/worker.rbs
temporalio/test/worker_activity_test.rb
temporalio/test/worker_workflow_test.rb

* Added `Temporalio::Worker#client` and `Temporalio::Worker#client=` to support replacing client on running worker
* Added `Temporalio::Activity::Context#client` to support accessing the client from the activity
1. Closes #165
1. Closes #181

Worker client replacement and activity client access

---

temporalio/.rubocop.yml
temporalio/lib/temporalio/client.rb
temporalio/lib/temporalio/client/interceptor.rb
temporalio/lib/temporalio/client/with_start_workflow_operation.rb
temporalio/lib/temporalio/error.rb
temporalio/lib/temporalio/internal/client/implementation.rb
temporalio/lib/temporalio/worker/thread_pool.rb
temporalio/sig/temporalio/client.rbs
temporalio/sig/temporalio/client/interceptor.rbs
temporalio/sig/temporalio/client/with_start_workflow_operation.rbs
temporalio/sig/temporalio/error.rbs
temporalio/sig/temporalio/internal/client/implementation.rbs
temporalio/test/client_schedule_test.rb
temporalio/test/client_workflow_test.rb
temporalio/test/worker_workflow_handler_test.rb
temporalio/test/worker_workflow_test.rb

* Added `Temporalio::Client::WithStartWorkflowOperation` class
* Added `start_update_with_start_workflow` and `execute_update_with_start_workflow` to client and all necessary plumbing
* Added `signal_with_start_workflow` to client and all necessary plumbing
1. Closes #188

Update with start and signal with start

---

temporalio/ext/src/runtime.rs
temporalio/lib/temporalio/activity/definition.rb
temporalio/lib/temporalio/internal/bridge/runtime.rb
temporalio/lib/temporalio/runtime.rb
temporalio/lib/temporalio/workflow/future.rb
temporalio/sig/temporalio/internal/bridge/runtime.rbs
temporalio/sig/temporalio/runtime.rbs

Added `Temporalio::Runtime::OpenTelemetryMetricsOptions#http` option. Can't really test this reasonably since it's all in Core and we haven't added explicit tests in other languages we have added this.
1. Closes #196

Support HTTP protocol for OTel metrics

---

temporalio/lib/temporalio/activity/definition.rb
temporalio/lib/temporalio/internal/worker/workflow_instance.rb

Use RawValue for built-in query response so user's payload converter is not used
1. Closes #224

Use RawValue for built-in query response

---

.github/workflows/nightly.yml
.github/workflows/run-bench.yml
temporalio/extra/simple_bench.rb
temporalio/temporalio.gemspec

Create simple/naive nightly benchmark that uses fibers. This is mostly a sanity test that Ruby performs well with some load, we just happen to run it nightly. No big surprises here. We use the same methodology as Python and .NET nightlies. For example, here is the 10000 workflow bench on the latest Ruby run compared to the last night's Python run and .NET run:
Ruby:
```
{workflow_count: 10000, max_cached_workflows: 10000, max_concurrent: 10000, max_mem_mib: 1464, start_seconds: 23.889, result_seconds: 117.192, workflows_per_second: 85.33}
{workflow_count: 10000, max_cached_workflows: 10000, max_concurrent: 10000, max_mem_mib: 1465, start_seconds: 23.253, result_seconds: 142.239, workflows_per_second: 70.304}
{workflow_count: 10000, max_cached_workflows: 1000, max_concurrent: 1000, …
```

Simple nightly benchmark

---

README.md
temporalio/Gemfile
temporalio/lib/temporalio/activity/definition.rb
temporalio/lib/temporalio/activity/info.rb
temporalio/lib/temporalio/client.rb
temporalio/lib/temporalio/client/with_start_workflow_operation.rb
temporalio/lib/temporalio/client/workflow_handle.rb
temporalio/lib/temporalio/contrib/open_telemetry.rb
temporalio/lib/temporalio/internal/client/implementation.rb
temporalio/lib/temporalio/internal/worker/workflow_instance.rb
temporalio/lib/temporalio/internal/worker/workflow_instance/context.rb
temporalio/lib/temporalio/internal/worker/workflow_instance/outbound_implementation.rb
temporalio/lib/temporalio/testing/activity_environment.rb
temporalio/lib/temporalio/workflow.rb
temporalio/lib/temporalio/workflow/info.rb
temporalio/sig/temporalio/client/interceptor.rbs
temporalio/sig/temporalio/client/with_start_workflow_operation.rbs
temporalio/sig/temporalio/contrib/open_telemetry.rbs
temporalio/sig/temporalio/internal/worker/workflow_instance/context.rbs
temporalio/sig/temporalio/worker/interceptor.rbs
temporalio/sig/temporalio/workflow.rbs
temporalio/sig/temporalio/workflow/info.rbs
temporalio/test/contrib/open_telemetry_test.rb
temporalio/test/sig/contrib/open_telemetry_test.rbs
temporalio/test/sig/workflow_utils.rbs
temporalio/test/workflow_utils.rb

* Moved resolving string from workflow/signal/query/update/activity definition to before interceptor instead of after (technically a backwards incompatible change)
* Added `Temporalio::Contrib::OpenTelemetry` module
* Includes `TracingInterceptor` class for tracing
* Includes `Workflow` module with helpers for replay-safe span creation
* Added concept of `Temporalio::Workflow.storage` akin to `Fiber#storage` where arbitrary data can be stored on a workflow
* Needed by the workflow helpers for OTel so they can store workflow-specific state, but may be used by other users doing similar type of stateful workflow helpers
* Added several tests which required a lot of effort on OTel testing harness/helpers
* Added lots of README information
1. Closes #189

OpenTelemetry tracing support

---

temporalio/ext/src/client.rs
temporalio/ext/src/metric.rs
temporalio/ext/src/runtime.rs
temporalio/ext/src/testing.rs
temporalio/ext/src/util.rs
temporalio/ext/src/worker.rs
temporalio/lib/temporalio/runtime.rb
temporalio/lib/temporalio/runtime/metric_buffer.rb
temporalio/sig/temporalio/internal/bridge/runtime.rbs
temporalio/sig/temporalio/runtime.rbs
temporalio/sig/temporalio/runtime/metric_buffer.rbs
temporalio/test/worker_workflow_test.rb

Added `Temporalio::Runtime::MetricBuffer` users can create with a size and set on `Runtime` to buffer metrics. They can call `retrieve_updates` on the buffer to get buffered metrics. This gives more freedom for users to do what they want with the metrics.
1. Closes #176

Buffered metric support

---

temporalio/lib/temporalio/contrib/open_telemetry.rb
temporalio/sig/temporalio/contrib/open_telemetry.rbs
temporalio/test/contrib/open_telemetry_test.rb
temporalio/test/sig/contrib/open_telemetry_test.rbs
temporalio/test/sig/workflow_utils.rbs
temporalio/test/workflow_utils.rb

* Added `always_create_workflow_spans` option to tracer and docs/README details to explain purpose. 
* Fixed test to account for the fact that signal can come before or after child _actually_ starts

Support parentless OTel workflow spans

---

temporalio/lib/temporalio/internal/worker/workflow_instance.rb
temporalio/lib/temporalio/internal/worker/workflow_instance/context.rb
temporalio/lib/temporalio/internal/worker/workflow_instance/details.rb
temporalio/lib/temporalio/internal/worker/workflow_instance/scheduler.rb
temporalio/lib/temporalio/internal/worker/workflow_worker.rb
temporalio/lib/temporalio/worker.rb
temporalio/lib/temporalio/worker/workflow_executor/thread_pool.rb
temporalio/lib/temporalio/worker/workflow_replayer.rb
temporalio/lib/temporalio/workflow.rb
temporalio/sig/temporalio/internal/worker/workflow_instance.rbs
temporalio/sig/temporalio/internal/worker/workflow_instance/context.rbs
temporalio/sig/temporalio/internal/worker/workflow_instance/details.rbs
temporalio/sig/temporalio/internal/worker/workflow_worker.rbs
temporalio/sig/temporalio/worker.rbs
temporalio/sig/temporalio/worker/workflow_replayer.rbs
temporalio/sig/temporalio/workflow.rbs
temporalio/test/sig/workflow_utils.rbs
temporalio/test/worker_workflow_test.rb
temporalio/test/workflow_utils.rb

* Added `Temporalio::Workflow::Unsafe.io_enabled` that accepts a block to have IO enabled for
* Added `unsafe_workflow_io_enabled` default-false bool option for workers/replayers
* Implemented `Fiber::Scheduler#io_wait` to fail with clear message if not enabled, or work via blocking IO when enabled
1. Closes #239

Support unsafe IO/io_wait inside workflows

---

temporalio/Cargo.lock
temporalio/lib/temporalio/internal/worker/workflow_instance.rb
temporalio/lib/temporalio/workflow/info.rb
temporalio/sig/temporalio/workflow/info.rbs
temporalio/test/worker_workflow_test.rb

* Added `Temporalio::Workflow::Info#root` as a nilable `RootInfo` that has a `workflow_id` and a `run_id`
* Update cargo dependencies in extension
1. Closes #227

Expose root execution info and update cargo deps

---

temporalio/ext/src/runtime.rs
temporalio/lib/temporalio/internal/bridge/runtime.rb
temporalio/lib/temporalio/runtime.rb
temporalio/sig/temporalio/internal/bridge/runtime.rbs
temporalio/sig/temporalio/runtime.rbs
temporalio/test/runtime_test.rb

Added `histogram_bucket_overrides` on `OpenTelemetryMetricsOptions` and `PrometheusMetricsOptions`, and added the Rust side and test.
1. Closes #228

Custom histogram metric buckets

---

temporalio/lib/temporalio/testing/workflow_environment.rb
temporalio/test/testing/workflow_environment_test.rb

1. Closes #259 
-  Made the change locally and it fixed the test I was writing in my application
-  Wrote a test for this PR
Failing Before Fix
Passing After Fix
4. Any docs updates needed?
An example using this helper would be nice but probably out of scope for this PR

Fix auto_time_skipping_disabled

---

temporalio/lib/temporalio/internal/worker/activity_worker.rb
temporalio/lib/temporalio/internal/worker/workflow_instance.rb
temporalio/lib/temporalio/internal/worker/workflow_instance/details.rb
temporalio/lib/temporalio/internal/worker/workflow_instance/outbound_implementation.rb
temporalio/lib/temporalio/internal/worker/workflow_worker.rb
temporalio/lib/temporalio/worker.rb
temporalio/lib/temporalio/worker/workflow_executor/thread_pool.rb
temporalio/lib/temporalio/worker/workflow_replayer.rb
temporalio/sig/temporalio/internal/worker/activity_worker.rbs
temporalio/sig/temporalio/internal/worker/workflow_instance.rbs
temporalio/sig/temporalio/internal/worker/workflow_instance/details.rbs
temporalio/sig/temporalio/internal/worker/workflow_worker.rbs
temporalio/sig/temporalio/worker.rbs
temporalio/test/worker_workflow_test.rb

Add workflow check that local activity exists
A missing local activity should fail the workflow task rather than the activity since it cannot succeed.
1. Closes #253 
New workflow tests
None

Add workflow check that local activity exists

---

temporalio/lib/temporalio/converters/failure_converter.rb
temporalio/lib/temporalio/error/failure.rb
temporalio/lib/temporalio/internal/worker/activity_worker.rb
temporalio/sig/temporalio/error/failure.rbs
temporalio/test/worker_activity_test.rb

Added `category` field and associated enum to `ApplicationError`.
Feature request: https://github.com/temporalio/features/issues/614
1. Closes #242
2. How was this tested: added benign failure test case to `worker_activity_test.rb#test_failure`.

Added application error category

---

.github/workflows/build-gems.yml
temporalio/Cargo.lock
temporalio/ext/.cargo/config.toml
temporalio/ext/Cargo.toml
temporalio/ext/src/client.rs
temporalio/ext/src/lib.rs
temporalio/ext/src/metric.rs
temporalio/ext/src/runtime.rs
temporalio/ext/src/testing.rs
temporalio/ext/src/util.rs
temporalio/ext/src/worker.rs

* Updated to Rust 2024 edition (and adjusted code to fix new lint issues)
* Updated all Cargo deps
* Replaced use of GH action `oxidize-rb/actions/cross-gem` with explicit invocation of `rb-sys-dock` so it can use updated Rust (see https://github.com/oxidize-rb/actions/issues/61) in `build-gems`
* Removed `macos-intel` (i.e. `macos-13`) from the `build-gems` smoke tests for now (see #306)
No runtime code was changed. All Rust code changes are simply a product of newer `cargo fmt` capabilities.

Update Rust edition and fix build-gems CI

---

README.md
temporalio/lib/temporalio/contrib/open_telemetry.rb
temporalio/lib/temporalio/converters/payload_converter/json_plain.rb
temporalio/lib/temporalio/internal/worker/workflow_instance/context.rb
temporalio/lib/temporalio/internal/worker/workflow_instance/replay_safe_logger.rb
temporalio/lib/temporalio/internal/worker/workflow_instance/scheduler.rb
temporalio/lib/temporalio/workflow.rb
temporalio/test/worker_workflow_test.rb

The main issue is there was a case where, in high-contention situations, a logger's mutex will block for a short little bit. Since we make mutexes durable, we completed the workflow task while the mutex was waiting and never resume the workflow to wake it up. We've made a couple of changes to help here.
<details>
<summary>Code to replicate</summary>
```ruby
require 'logger'
require 'temporalio/client'
require 'temporalio/testing'
require 'temporalio/worker'
workflow_count = 500
logger = Logger.new($stdout)
class HangingTimersWorkflow < Temporalio::Workflow::Definition
workflow_query_attr_reader :done
def execute
Temporalio::Workflow.logger.info 'Started demo timers workflow'
5.times.each do |i|
Temporalio::Workflow.logger.info("Timer fut #{i}")
timer_fut(seconds: 1).wait
end …
```

Fix issue with high-contention mutex causing hung workflows

---

temporalio/lib/temporalio/internal/worker/workflow_instance/externally_immutable_hash.rb
temporalio/lib/temporalio/workflow.rb

Added some `require` calls.
We can't catch these well in our tests due to how Ruby caches imports, so it only fails on certain samples that use minimal imports. And even then, it's only certain samples. This was found when doing release sanity tests. We can look into possibly including some sample smoke tests in CI, but it still won't catch every needed require (and it's not a bug per se, a user just has to import a bit more sometimes if we don't do it for them). Just an unfortunate Ruby situation where we can't tell which requires are needed exactly.

Add some require calls for newer code

---

temporalio/lib/temporalio/activity/info.rb
temporalio/lib/temporalio/internal/worker/activity_worker.rb
temporalio/lib/temporalio/testing/activity_environment.rb
temporalio/sig/temporalio/activity/info.rbs
temporalio/test/test.rb
temporalio/test/worker_activity_test.rb

- Added retry policy to activity info.
- Upgraded Core to latest version, which is needed for activity retry policy to be filled in correctly.
- Small correction to test base class so it doesn't crash when target host env var is nil.
Feature request: https://github.com/temporalio/features/issues/615
1. Closes #248
Added assertion to `test_info` in `test/worker_activity_test.rb`.

Added retry policy to activity info

---

temporalio/lib/temporalio/internal/worker/workflow_instance/context.rb
temporalio/lib/temporalio/internal/worker/workflow_instance/outbound_implementation.rb
temporalio/lib/temporalio/worker/interceptor.rb
temporalio/lib/temporalio/workflow.rb
temporalio/sig/temporalio/internal/worker/workflow_instance/context.rbs
temporalio/sig/temporalio/worker/interceptor.rbs
temporalio/sig/temporalio/workflow.rbs
temporalio/test/worker_workflow_activity_test.rb

- Added option to set local activity summary.
- Added activity and local activity summary tests.
Feature request: https://github.com/temporalio/features/issues/637
1. Closes #298
Added `test_activity_summary` and `test_local_activity_summary` to `test/worker_workflow_activity_test.rb`.

Added option to set local activity summary. Added activity summary tests

---

README.md
temporalio/Cargo.lock
temporalio/ext/Cargo.toml
temporalio/ext/src/lib.rs
temporalio/ext/src/runtime.rs
temporalio/ext/src/worker.rs
temporalio/lib/temporalio/internal/bridge/worker.rb
temporalio/lib/temporalio/worker/tuner.rb
temporalio/sig/temporalio/internal/bridge/worker.rbs
temporalio/sig/temporalio/worker/tuner.rbs
temporalio/test/sig/worker_test.rbs
temporalio/test/sig/workflow_utils.rbs
temporalio/test/worker_test.rb
temporalio/test/workflow_utils.rb

* Added ability to provide `Temporalio::Worker::Tuner::SlotSupplier::Custom` instances for slot suppliers
* Added bridge/Rust code to support custom slot suppliers
1. Closes #225

Custom slot suppliers

---

temporalio/lib/temporalio/converters/payload_converter/json_protobuf.rb
temporalio/test/converters/payload_converter_test.rb

Mark the JSON value as binary before assigning to `data` key in `Api::Common::V1::Payload`.
Ruby protobuf uses ASCII-8BIT encoding for `bytes` fields in proto messages. The protobuf gem will attend to force the encoding from UTF8 to ASCII-8BIT when assigning the value, but when UTF8 has multi-byte characters (like an emdash), it fails.
LLM's _love_ the emdash, so when I was attempting to switch from coinbase's library to this one, I hit issues with the encoding problem. I had commented on this PR on Coinbase's PR which had the same exact problem: https://github.com/coinbase/temporal-ruby/pull/264
I added tests to demonstrate the problem, if you remove the `.b` in the changes you'll see them fail.

bugfix: Mark json value as binary before assigning to  field in payload

---

temporalio/ext/src/client.rs
temporalio/test/client_test.rb

Need to support `-bin` values as binary values in gRPC
1. Closes #329

Support binary values in gRPC metadata
